# Generated by Django 2.2.17 on 2020-12-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_gghhh"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ghfdgfdgfd",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hgfhfh", models.BigIntegerField()),
            ],
        ),
    ]
