# Generated by Django 2.2.17 on 2020-12-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homejhgjhgjg", "0001_initial"),
        ("cfhfdh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fghgjyj",
            name="adsfvaevdcz",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fghgjyj_adsfvaevdcz",
                to="homejhgjhgjg.JHGjfhg",
            ),
        ),
    ]
