# Generated by Django 2.2.17 on 2020-12-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homejhgjhgjg', '0001_initial'),
        ('cfhfdh', '0002_fghgjyj_adsfvaevdcz'),
    ]

    operations = [
        migrations.AddField(
            model_name='fghgjyj',
            name='dcvae',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fghgjyj_dcvae', to='homejhgjhgjg.JHGjfhg'),
        ),
    ]
